import Head from "next/head";
import Image from "next/image";
import artist from "../public/artist-login.svg";
import google from "../public/google.svg";
import Link from "next/link";
import { useState, useEffect } from "react";
import {
  useSessionContext,
  useSupabaseClient,
  useUser,
} from "@supabase/auth-helpers-react";
import { useRouter } from "next/router";

export default function SignIn() {
  const [email, SetEmail] = useState("");
  const [password, SetPassword] = useState("");
  const { push } = useRouter();
  const supabaseClient = useSupabaseClient();
  const user = useUser();

  useEffect(() => {
    if (user) {
      push('/');
    }
  }, [user]);

  
  const signInWithGoogle = async (e:any) => {
    e.preventDefault();
    const { data, error } = await supabaseClient.auth.signInWithOAuth({
      provider: "google",
      options: {redirectTo: 'http://localhost:3000'}
    });
  };
  const supabaseSignIn = async (e:any) => {
    e.preventDefault();
    const { data, error } = await supabaseClient.auth.signInWithPassword({
      email: email,
      password: password,
    });
  };

  return (
    <>
      <Head>
        <title>SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen overflow-hidden flex flex-col justify-center items-center bg-signIn object-cover bg-cover">
        <section className="w-fit flex p-1 md:p-0 flex-row  bg-secondary md:drop-shadow-glowHigh rounded-3xl">
          <div className="w-96 h-96 xl:w-[520px] xl:h-[520px] hidden md:flex">
            <Image
              src={artist}
              alt="artist"
              className="h-full w-full drop-shadow-glowHigh"
            />
          </div>
          <div className=" h-96 w-96 xl:w-[580px] xl:h-[600px] p-8 m-2 xl:p-16 rounded-3xl bg-primary drop-shadow-glow ">
            <h1 className="text-4xl xl:text-[52px] text-heading drop-shadow-glow font-Inter ">
              Sign-In
            </h1>
            <form
              className="flex flex-col w-full h-fit justify-center items-center mt-10 xl:mt-20 gap-4"
              id="signIn"
              onSubmit={supabaseSignIn}
            >
              <input
                className="input-field"
                placeholder="Email"
                type="email"
                onChange={(e) => SetEmail(e.target.value)}
              />
              <input
                className="input-field"
                placeholder="Password"
                type="password"
                onChange={(e) => SetPassword(e.target.value)}
              />
              <button type="submit" form="signIn" className="btn-secondary">
                Sign-In
              </button>
              <p className="font-Inter mt-2 text-sm xl:text-xl xl:mt-16 text-heading">
                Don't have an Account?{" "}
                <Link
                  href="/register"
                  className="text-interactive text-md font-Inter drop-shadow-glowHigh underline"
                >
                  Register
                </Link>
              </p>
            </form>
          </div>
        </section>
        <div className="mt-8">
          <Image
            src={google}
            alt="google"
            className="icon"
            onClick={signInWithGoogle}
          />
        </div>
      </main>
    </>
  );
}
